---
deploy__app_download_link: https://storage.yandexcloud.net/final-homework/bingo
deploy__app_dir: /opt/bingo
deploy__app_binary_name: bingo
deploy__system_user_name: bingo
deploy__system_group_name: bingo
deploy__app_version: 20231121T1537

deploy__app_config_email: test123@example.com
deploy__app_config_db_address: 192.168.50.30
deploy__app_config_db_port: 5432
deploy__app_config_db_user: postgres
deploy__app_config_db_password: ""
deploy__app_config_db_name: bingo

deploy__app_config_file_dir: /opt/bingo
deploy__app_run_prepare_db_task: false


deploy__app_slow_start_hack: true
